version: "3"

services:
  musicbot:
    build: .
    container_name: musicbot
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data 
      - ./temp:/app/temp
    restart: unless-stopped
